import './globals.css'
import NavBar from './components/navbar'

export const metadata = {
  title: 'Erics Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  )
}
